\
                /* This file was generated by blade */
                extern "C" {
                namespace binary_version {
                extern const int kSvnInfoCount = 1;
                extern const char* const kSvnInfo[] = {"unknown@unknown\n"};
                extern const int kScmInfoCount = 1;
                extern const char* const kScmInfo[] = {"unknown@unknown\n"};
                extern const char kBuildType[] = "release";
                extern const char kBuildTime[] = "Tue Jun 21 19:37:35 2022";
                extern const char kBuilderName[] = "zhuchun";
                extern const char kHostName[] = "zhuchun-virtual-machine";
                extern const char kCompiler[] = "gcc 7";
                }}