/* This file was generated by blade */

extern const int kSvnInfoCount;
extern const char* const kSvnInfo[];
extern const char kBuildType[];
extern const char kBuildTime[];
extern const char kBuilderName[];
extern const char kHostName[];
extern const char kCompiler[];
const int kSvnInfoCount = 2;
const char* const kSvnInfo[2] = {"git@github.com:general-zhu/webServer.git\n"
"* master\n"
"commit 822c4ad0a83a940006c76b5b08f8b3d5e92527c3\n"
"Merge: 23d9f90 b77dd9a\n"
"Author: general-zhu <51484494+general-zhu@users.noreply.github.com>\n"
"Date:   Thu Jun 16 19:44:02 2022 +0800\n"
"\n"
"    Merge pull request #12 from general-zhu/zhuchun7\n"
"    \n"
"    添加muduo库\n"
"", "git@github.com:general-zhu/webServer.git\n"
"* master\n"
"commit 822c4ad0a83a940006c76b5b08f8b3d5e92527c3\n"
"Merge: 23d9f90 b77dd9a\n"
"Author: general-zhu <51484494+general-zhu@users.noreply.github.com>\n"
"Date:   Thu Jun 16 19:44:02 2022 +0800\n"
"\n"
"    Merge pull request #12 from general-zhu/zhuchun7\n"
"    \n"
"    添加muduo库\n"
""};
const char kBuildType[] = "release";
const char kBuildTime[] = "Sun Jun 26 12:17:58 2022";
const char kBuilderName[] = "zhuchun";
const char kHostName[] = "zhuchun-virtual-machine";
const char kCompiler[] = "GCC 7";
